FROM ubuntu

ENV PATH="/tmp/apache-maven-3.6.0/bin:${PATH}"

WORKDIR /tmp
RUN apt-get update && \
	apt-get install git sed wget openjdk-11-jdk -y --no-install-recommends && \
	wget https://archive.apache.org/dist/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz && tar xzf apache-maven-3.6.2-bin.tar.gz && \
	export PATH=/tmp/apache-maven-3.6.2/bin:${PATH}